### PR TITLE
Fix compatibility with Angular 10

### LINKED ISSUE #29: Angular 10: Cannot find module '@schematics/angular/utility/project'
I'm using this library as part of [@oktadev/schematics](https://github.com/oktadeveloper/schematics). Today, I tried upgrading to Angular 10 and now I get the following stack trace when I try to install my schematic. It seems like the error is caused by this project, but I'm not sure.

```
Cannot find module '@schematics/angular/utility/project'
Require stack:
- /Users/mraible/ng10/node_modules/@angular/cdk/schematics/utils/build-component.js
- /Users/mraible/ng10/node_modules/@angular/cdk/schematics/utils/index.js
- /Users/mraible/ng10/node_modules/@angular/cdk/schematics/index.js
- /Users/mraible/ng10/node_modules/schematics-utilities/dist/material/ast/ng-module-imports.js
- /Users/mraible/ng10/node_modules/schematics-utilities/dist/material/index.js
- /Users/mraible/ng10/node_modules/schematics-utilities/dist/index.js
- /Users/mraible/ng10/node_modules/@oktadev/schematics/src/add-auth/index.js
- /Users/mraible/ng10/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/mraible/ng10/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/mraible/ng10/node_modules/@angular/cli/utilities/json-schema.js
- /Users/mraible/ng10/node_modules/@angular/cli/models/command-runner.js
- /Users/mraible/ng10/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
```

### PR DESCRIPTION
**Pull request by mraible**
Fixes #29 and #22.

### CODE REVIEW

**Comment by mraible** [comment]
I integrated it into @oktadev/schematics. The passing CI tests prove it works: https://github.com/oktadeveloper/schematics/pull/360. 🙂

**Comment by nitayneeman** [comment]
Thank you very much for your contribution!
I'll do an extra check that everything is fine and make a release. 😊

As a side note (and as a consumer of this package) - what do you think about https://github.com/nitayneeman/schematics-utilities/issues/32? Would you like to get a reduced dependency graph by having `peerDependencies` instead or might it restrict your usage in some way?

**Comment by mraible** [comment]
> As a side note (and as a consumer of this package) - what do you think about #32? 

If you can create a PR for this change, I can try it with @oktadev/schematics and see if it breaks anything.

**Comment by nitayneeman** [comment]
> > As a side note (and as a consumer of this package) - what do you think about #32?
> 
> If you can create a PR for this change, I can try it with @oktadev/schematics and see if it breaks anything.

Great, I'll make one.

But before that, we need to bring back `@angular/cdk` clone because of https://github.com/nitayneeman/schematics-utilities/issues/17. I'll update this clone and make a PR so you could verify it works with @oktadev/schematics.

**Comment by mraible** [comment]
@nitayneeman I removed the clone of `@angular/cdk` because it causes [this issue](https://github.com/nitayneeman/schematics-utilities/issues/22). I've never been able to use 2.0.1 because of this.

**Comment by nitayneeman** [comment]
> @nitayneeman I removed the clone of `@angular/cdk` because it causes [this issue](https://github.com/nitayneeman/schematics-utilities/issues/22). I've never been able to use 2.0.1 because of this.

@mraible If I understand correctly, https://github.com/okta/okta-oidc-js/issues/643 was caused mainly because of missing support of @okta/okta-angular in Angular v9. It's supposed to be OK today according to https://github.com/okta/okta-oidc-js/issues/643#issuecomment-573177222.

I created a [PR](https://github.com/nitayneeman/schematics-utilities/pull/35) with the clone of the CDK - could you give it a try?

And thanks again for your assistance, very appreciated.

**Pull request merged**
