### PR TITLE
[buildComponent] Fix Interfaces usage from buildComponent

### PR DESCRIPTION
**Pull request by norato**
Screen Shot 2019-08-11 at 12 00 27

### CODE REVIEW

**Comment by nitayneeman** [comment]
Hey, 

Thank you for your contribution! 😊
I've planned to upgrade the packages a while ago.

Have you had a chance to verify that the project is transpiled without any error after running `npm run build`? 

By the way, I added a simple CI check for that - so you can just merge from master.

**Comment by norato** [comment]
Hey, @nitayneeman.
I don't have the write permission to merge to master.

**Comment by nitayneeman** [comment]
I'm happy to announce that [v2.0.0](https://github.com/nitayneeman/schematics-utilities/blob/master/CHANGELOG.md#200---2019-10-05) has been released!
As part of this release, the interfaces were fixed for all of the utilities (including `buildComponent`).

Would you like to give it a try?

**Comment by norato** [comment]
@nitayneeman I will try it

**Pull request closed without merging**
